### ISSUE TITLE
Discussion about how to handle deeply nested dataloader

### ISSUE THREAD

**Issue by Un3qual** [absinthe-graphql/dataloader#112]
I have a graphql query that looks like this (simplified)
```graphql
posts { # Type of [Post]
  body
  viewerHasLiked
  comments { # Type of [Post] (but just has parent_id column or something)
    body
    viewerHasLiked
    replies { # Type of [Post] 
      body
      viewerHasLiked
    }
  }
}
```
I am using Dataloader for the associations and for the `viewerHasLiked` field. Unfortunately, when this query is run, Dataloader runs the query for `viewerHasLiked` twice. Once for the post and its comments, and once for the comments' replies. I have been trying to figure out a way to merge this all into one query and it ended up bringing me to `Absinthe.Middleware.Dataloader`. It looks like, if I understand correctly, before the field is to be resolved, the plugin calls `Dataloader.run/1` on the loader in the context. Then when the middleware is called, it checks if batches are still pending (if the Dataloader has finished running?). If there are none pending, it returns the result from Dataloader and if there are still batches, it sets the field's state to `:suspended` and adds a middleware to that field to call it again, and that is when it returns the result.

The issue is that when `Dataloader.run/1` in `before_resolution/1` is called, it fetches for all the existing batches (including for `viewerHasLiked`), but it has only resolved posts and comments so far. I'm not really sure how this would be approached because Dataloader has to load the stuff for comments and replies in order to have the ids to use for loading `viewerHasLiked`.

It could be some kind of priority system where things with a higher priority (posts, comments, replies) would be resolved first, and then something with a lower priority (`viewerHasLiked`) would be resolved last. This might require extensive rearchitecting of absinthe because it would have to resolve in multiple passes, depth first, instead of breadth first. I'm not sure though.

We could also have a `Dataloader.run/2` that selectively fetches. It could group things together by their object and look at both the schema and what's being requested in the query or mutation. With this information, it could do passes where it tries to resolve as much as possible until it can't anymore and then resolve the fields with Dataloader middleware by looking at what child fields are requested. Here's an example using the query above:

1. Resolves the root `posts`
2. Resolves `body`
3. Tries to resolve `viewerHasLiked`, but it's a Dataloader field so it suspends
4. Tries to resolve `comments`, but it's a Dataloader field so it suspends
5. Now it starts to resolve Dataloader fields. it looks at the query and sees that one of `comments`'s child fields is `viewerHasLiked`, so it resolves (and fetches from DB) `comments` first
6. It does a pass on `comments`' children. It can resolve `body`, but not `viewerHasLiked`.
7. It tries to resolve `replies`, but it's a Dataloader field, so it can't. It has nothing more to resolve so it starts on the Dataloader fields
8. It looks at what the children of `replies` are, and it sees `viewerHasLiked`, so it resolves (and fetches) `replies` first. 
9. Now it can resolve the `replies`' body
10. Finally it fetches `viewerHasLiked` with the ids from every level, running a single query. It can resolve the `replies`' `viewerHasLiked`
11. There's nothing more to resolve at this level so it goes back to the top and resolves `posts`' `viewerHasLiked` and then `comments`' `viewerHasLiked`

I'm pretty familiar with Dataloader's internals, but not as much with Absinthe's. If someone who knows more about how Absinthe words could provide their input this would be much appreciated.

**Comment by Un3qual** [comment]
Thinking about it even more, if we're gonna go the route of walking the whole tree (or walking all of a field's children depth first) ahead of time to know what to wait for and what to fetch now, it might be worth adding the ability to choose between joins or batches, because in a lot of cases, joins might be more efficient.

**Comment by tlvenn** [comment]
Hi @Un3qual ,

You should read this topic: https://github.com/absinthe-graphql/absinthe/issues/269 , I believe it will contrast with your intuition. Both approaches have different trade offs.

**Comment by benwilson512** [comment]
Here's the thing. What you're asking for isn't _strictly speaking_ impossible, but it's quite hard for two reasons:

1) Resolvers are opaque to Absinthe. They're a stack of functions that contain and execute arbitrary code, Absinthe cannot easily know that partial resolution of suspended fields will be better than complete resolution of suspended fields. Right now Absinthe has an execution flow. What you would need to do is write a custom Resolution phase module that could utilize Dataloader specific information to adjust how resolution works. 

2) Global query optimizers are very hard.

This is a fine idea at some level, but this is definitely not a bug in Absinthe and is well, well beyond anything that is part of the Absinthe roadmap. It also, strictly speaking, does NOT need to be in Absinthe core. All Absinthe phases are replaceable, and they're replaceable by plugins dynamically too, so you could write your own version of this as a separate package, give it a whirl, and if that pans out we can look at adding it to core.

The Absinthe core team has worked very hard to make Absinthe extendable, precisely so that when people want to try stuff like this, they are not bottlenecked by the core team. I'll be happy to weigh in on the forum post, but the issue tracker we try to reserve for bugs and concrete roadmaped features.
