### ISSUE TITLE
Would it be possible to get a release published?

### ISSUE THREAD

**Issue by zachdaniel** [absinthe-graphql/dataloader#151]
Because we can't prevent the underlying dataloader from being async, we have some flaky tests in `ash_graphql`. We can't use a github dependency because then we can't publish `ash_graphql` on hex :).

**Comment by mbuffa** [comment]
+1 for a release please 🙏 .

With dataloader 1.0.10, running a GraphQL query with dataloader loading associations results in incorrect OpenTelemetry events (the GraphQL query gets its own context, but it only contains two spans related to the main SQL queries; SQL queries sent for loading associations are sent as separate events). This got fixed with commit `73ff608a24e24cc0742f2c657d2ae7241e4048a9` (I assume because of the recent ecto_sql update or something related).

**Comment by benwilson512** [comment]
v1.0.11 has been released. I'll get a v2.0 shortly that does the async automatically.
