### ISSUE TITLE
Dataloader Ecto: Prevent reuse of a preloaded child

### ISSUE THREAD

**Issue by jfrolich** [absinthe-graphql/dataloader#18]
The Ecto loader caches the existing associations if they are already loaded. I think a better behaviour is to explicitly cache them such as the Absinthe helper looks to support with this code:

```elixir
  def use_parent(loader, resource, parent, args, opts) do
    with true <- Keyword.get(opts, :use_parent, false),
         {:ok, val} <- is_map(parent) && Map.fetch(parent, resource) do
      Dataloader.put(loader, Ectoloader, {resource, args}, parent, val)
    else
      _ -> loader
    end
  end
```

However even if `use_parent` is false the value will still be cached.

The below code. If `parent` already contains `resource` a query will not be made:

```elixir
loader
|> Dataloader.load(Context, {resource, args}, parent)
|> on_load(fn loader ->
   {:ok, Dataloader.get(loader, Context, {resource, args}, parent)}
end
```

**Comment by benwilson512** [comment]
Do you have an isolated test case that shows this? I'm not seeing any code in the ecto source that would do this.

**Comment by benwilson512** [comment]
For posterity: This was happening due to how `Repo.preload` works. If there are any existing values, `Repo.preload` just no-ops. Neither Dataloader nor ecto were doing any explicit caching, but it still acted that way due to the Ecto functionality.

I'm leaning towards having Dataloader act consistently and always query unless you've explicitly set the dataloader cache, which is what the linked PR does.

**Comment by jfrolich** [comment]
Thanks for having a chat about this on Slack @benwilson512 and coming to the root of the problem. It's nice to be able to make sure the associations are loaded correctly even though there might be preloads hanging around.
