### ISSUE TITLE
[Ecto] Support for associations which uses through

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/dataloader#5]
> https://hexdocs.pm/ecto/Ecto.Schema.html#has_many/3-has_many-has_one-through

Right now a RuntimeError saying the association cannot be found in the schema is raised.

**Comment by tlvenn** [comment]
@benwilson512 do you think there is a way to resolve this without leveraging a through ? With absinthe_ecto I was able to provide a custom callback that would return the desired object.

I am not sure there is a workaround for that in the Dataloader at the moment.

**Comment by tlvenn** [comment]
As discussed with @benwilson512 , let me illustrate the problem I have with a concrete example:

So we have on ecto side, an `activity` schema which has 1 `cover` which is an `asset_link` which has 1 `asset`:
> Activity <--> AssetLink <--> Asset

On graphql side, the activity object `cover`'s field points directly to the asset and is not returning the intermediate asset_link which is invisible:
> `Activity <--> Asset`

So I am trying to dataload the assets for a collection of activities.

At first I though I could simply manually dataload `Asset` by passing in a batch key I create and using the args to build a query that would join on `asset_link` and select the proper `asset_link.id` I get from the `activity` (the parent).

The issue with this approach is the logic of the `Dataloader.Ecto` will try no matter what to manipulate the queryable on its own which is not needed in this case since I have done all the work already to select it properly.

So once I saw I could not use this approach, I though about creating a through association in `activity` Ecto schema and let Ecto deal with it, then I realised that the dataloader was not handling through associations.

So most probably the dataloader should handle through associations and I also wonder if I shouldn't be able to execute on the first idea that I had and using an flag let the dataloader know that all the work is done to select the object and that it should not try to further manipulate the queryable.

**Comment by tlvenn** [comment]
Actually regarding the first approach, it is natural that the dataloader is trying to alter the queryable, that is its way to batch load ;)

So I guess the default predicate is to do it on the primary key of the schema being loaded as seen here: https://github.com/absinthe-graphql/dataloader/blob/master/lib/dataloader/ecto.ex#L248

maybe we could provide a fun to customize this which would take the queryable and the `ids` like this:
```elixir
fn queryable, ids, do: from [a,l] in queryable, where: l.id in ^ids
```

**Comment by tlvenn** [comment]
@benwilson512 any idea how to best solve this ? What do you think about my proposal of being able to provide the fun that does the dataloader selection ?

**Comment by benwilson512** [comment]
I think providing a function is useful, but I'd like to be able to handle through associations without any extra work like that. Why do through associations not match the queryable line?

**Comment by tlvenn** [comment]
Ya I agree, we should support through associations transparently. In my case, I would prefer not to leverage them because I dont really need it and I would rather not have to create though associations just to address my current need.

**Comment by benwilson512** [comment]
@tlvenn Looking at this today, quick question for you. To make sure I understand you correctly, the overall goal is to be able to load a bunch of Assets by feeding Dataloader a bunch of Activity ids.

Right now the options are
1) load something by primary key
2) load things by association.

Setting aside #2 for a moment, here are the challenges with extending #1. If we want to load something by not the primary key, we need a way to _indicate_ what column to load it on. This is similar to the question of "what if we wanted to load something by slug". Let's consider that simpler case for a second, and a possible solution:

```
loader
|> Dataloader.load(:foo, ContainerType, {:slug, "pallet"})
|> Dataloader.load(:foo, ContainerType, {:slug, "carton"})
|> Dataloader.load(:foo, ContainerType, {:id, 1})
```
This would produce the following SQL query:

```
SELECT * FROM container_types WHERE slug IN ("pallet", "carton") OR id IN (1)
```
Now, extending that to your situation you'd call `load/4` with `{:activity_id, activity.id}` and then also specify a batch function (which doesn't exist yet).

The primary downside with this is that the `batch` function has to be reasonably intelligent, since it needs to handle heterogenous ids 

```
source = Dataloader.Ecto.new(batch: &batch/2)

loader
|> Dataloader.add_source(source, :foo)
|> Dataloader.load(:foo, Asset, {:activity_id, activity1.id})
|> Dataloader.load(:foo, Asset, {:activity_id, activity2.id})
|> Dataloader.load(:foo, Asset, some_asset_id) # this will default to `{primary_key, some_asset_id}`

# elsewhere
def batch(Asset, ids) do
  ids
  |> Enum.group_by(&elem(&1, 0), &elem(&1, 1))
  |> Enum.reduce(Asset, fn
    {:activity_id, ids}, query ->
      from q in query, join: a, ..., where: a.id in ^ids
    {column, values}, query ->
      from q in query, where: field(q, ^column) in ^values
  end)
end
```

Note that we have the explicit pattern for `{:activity_id` that lets us do a join to the other table.

Does this seem like a reasonable solution?

**Comment by benwilson512** [comment]
Update on this: after some effort on this I think the callback would look more like:

```
def build_batch(Asset, query, :asset_link_id, ids) do
  from q in query,
    left_join: l in assoc(q, :asset_links),
    where: l.id in ^ids
end
def build_batch(type, query, field, ids) do
  Dataloader.Ecto.build_batch(type, query, field, ids)
end
```

Trying to compose multiple possible loadings via `or_where` ends up being prohibitively complex.

**Comment by tlvenn** [comment]
Ya looks great @benwilson512

**Comment by tlvenn** [comment]
@benwilson512 did you end up working on the proposal you are outlining above ?

**Comment by benwilson512** [comment]
Hey folks, here's where we're at. Ultimately, I'm requiring that the `load_batch` function actually does the Repo call itself. It's the only way to really let users customize how they retrieve stuff.

The complication happens in that there are really two modes of loading. One by association, and the other by queryable. For the purposes of the following examples, consider these situations:

```
# load Category ID 1
|> Dataloader.load(source, Category, [id: 1])

# If no column is specified, it defaults to the primary key of Category such that this is possible.
# This example here is normalized to be the same as the previous example
|> Dataloader.load(source, Category, 1)

# load Category with slug column "default"
|> Dataloader.load(source, Category, [slug: "default"]

# load category from post
|> Dataloader.load(source, :category, post)
```

As I got to thinking about this, I was increasingly convinced that there isn't any value in trying to enable customized batch loading for associations. More on this later. The point for now is, if you specify a `load_batch/4` function it'll be called for the three `Category` examples above, but not for `:category`. If you're using the Ecto association `:category` then that's what you'll get.

Anyway, the contract for the `load_batch` function is: return results in the same order as the input. Think of it like the same contract as `Enum.map`. For each input item, you'll get some output value.

Here is a simple example:

```
source = Dataloader.Ecto.new(Repo, query: &query/2, load_batch: &load_batch/4)

def query(queryable, _args) do
  # apply filters here
  queryable
end

def load_batch(Category, query, inputs, repo_opts) do
  ids = Enum.uniq for [id: id] <- inputs, do: id

  categories =
    query
    |> where([c], c.id in ^ids
    |> Repo.all(repo_opts)

  for [id: id] <- inputs do
    Enum.find(categories, fn category -> category.id == id end)
  end
end
def load_batch(queryable, query, inputs, repo_opts) do
  Dataloader.Ecto.load_batch(queryable, query, inputs, repo_opts)
end
```

`query` is the result of whatever filtering or what not was added on in the `query/2` function.
`inputs` is the aggregated values
`repo_opts` handles stuff like the `caller` option.  Generally folks can just leave it alone, but it is important to use.

The notable thing about `load_batch` is that you're going to get ALL desired columns. This is to say, if you do:

```
|> Dataloader.load(source, Category, [id: 1])
|> Dataloader.load(source, Category, [slug: "default"]
```

You're going to get `[[id: 1], [slug: "default"]]` as the input for the batch. This helps you minimize the number of database queries. The previous example didn't really handle that, it was just built for IDs. When you're doing something very specific that's totally fine, but here's a more generic version:

```
def load_batch(Category, query, inputs, repo_opts) do
  columns = Enum.group_by(inputs, fn [{col, _}] -> col end, fn [{_, val}] -> val end)

  query = Enum.reduce(columns, query, fn {col, values} ->
    query |> or_where([c], field(c, ^col) in ^Enum.uniq(values)
  end)

  categories = Repo.all(query, repo_opts)

  for [{col, value}] <- inputs do
    Enum.find(categories, fn category -> Map.get(category, col) == value end)
  end
end
```

It is completely fine to make multiple database requests inside this function. Sometimes that's what you'll need to do if you're doing some funky joins. You've still avoided doing N+1.

Thoughts?

**Comment by benwilson512** [comment]
Ok, I have a working implementation of this. The primary issue at this point is cardinality. Everything at this point assumes that for a given input like `|> Dataloader.load(source, Category, [id: 1])` that there is a single result. If we did something like `|> Dataloader.load(source, Post, [category_id: 1])` then there will plainly be a lot of posts for that given category.

Options:

1) `|> Dataloader.load(source, {:many, Post}, [category_id: 1])`
2) `|> Dataloader.load(source, %Dataloader.Batch{cardinality: :many, key: Post}, [category_id: 1])`
3) ... ?

Thoughts?

**Comment by tlvenn** [comment]
Great work @benwilson512 , I like where this is going !

In case of cardinality, I like option 1 which uses a ecto ish syntax.

There is one thing which i am not too sure about regarding the new shape of the batch function. The added benefit on the new shape is that you can handle things like `[[id: 1], [slug: "default"]]` in one query only which is great when you are batching using fields of the targeted model.

However, if you are batching using fields for different models that are joined to the targeted model somehow, it becomes impossible to do it with one query efficiently. You gonna have to use left outer join always and force the database to go through crazy number of joins.

In this situation, you really want / need a batch function for each kind of related models you are using as starting point. So ideally you want to be able to pattern match on the related model field being used to build a dedicated batch.

The old batch proposal with:
```elixir
def build_batch(Asset, query, :asset_link_id, ids) do
```
was offering such possibility at the cost of not being able to handle the case of `[[id: 1], [slug: "default"]]` with one query.

Could the input of the `load_batch` be a map with such shape:
```elixir
%{
  id: [1],
  slug: ["default"]
}
```

This would let the user pattern match on it to provide dedicated `load_batch` when needed and otherwise would already provide the collections of values to build a single query easily.

What do you think ?

**Comment by tlvenn** [comment]
Well I spoke too soon, that wouldn't work just like that either given the `load_batch` will be called only once with all the inputs..

But I guess you understand my dilemma ;)

**Comment by benwilson512** [comment]
Right. I think the solution to your situation is just documenting that it's possible to do multiple Repo calls in a single call to `load_batch` IE:

```
def load_batch(Category, query, inputs, repo_opts) do
  columns = Enum.group_by(inputs, fn [{col, _}] -> col end, fn [{_, val}] -> val end)
  for {column, values} <- columns do
    # load a single batch as before, doing one Repo.all call per column/values group
  end
end
```

There's already a Dataloader.pmap function that's tailored to how you want to do parallelism with dataloader so you could use that instead of the `for`.

On the subject of cardinality, if we go with `{:many, Post}` or `{:one, Category}` there's a question of defaults, and there's a question of how it shows up in `load_batch`.

### Cardinality Defaults

Whatever we decide, the simplest case where we're loading records by their primary keys shouldn't mandate a `:one` annotation.

Option 1) We default to `:many` for everything except primary keys.

Option 2) We default to `:one` for everything, and raise if you pass 

Option 3) No defaults except primary keys, you always need to pass in `:many` or `:one`, otherwise Dataloader will yell at you.

Option 1 has the nice feature of being the most compatible. IE, `[] | [item]` works for even a single item and multiple items, where as `item | nil` explodes if there are multiple items.

Option 2 I don't like

I can't tell if Option 3 is annoying and verbose or clear and explicit.

Fortunately as I've thought about it more I think we can at least avoid having to push `:one` or `:many` into `load_batch` entirely. I'll just use it when processing the output of `load_batch` and act accordingly there.

**Comment by tlvenn** [comment]
Ha great yes indeed, it's definitely not as simple as pattern matching on the batch fun itself but definitely doable.

As for the cardinality default, I agree with you, the choice is between 1 & 3. Given this is already a highly specialised batching feature that you not gonna use all over the place, I would probably be on the side of being clear and explicit.

**Comment by stephenmoloney** [comment]
FWIW, I like option 3 but i tend to prefer being explicit in general. Also, it's educational.

**Comment by benwilson512** [comment]
@tlvenn you'll be pleased to know that I'm doing away with the "grouping all the columns" thing. It was hard to use, and even more importantly I don't think it's possible to actually use correctly. If you join stuff to the query with `or_where` then filtering is impossible, because it works out to `(condition1 AND condition2 AND ...) OR (id in [1,2,3])` which permits rows with `id` 1, 2, or 3 regardless of whether they match the conditions or not.

So with that in mind here is an example from the tests: https://github.com/absinthe-graphql/dataloader/pull/11/files#diff-4e26394bbe4c01e5464643509e9bc906R41

I should probably turn `run_batch(User, query, {:post_title, titles}, repo_opts)` into `run_batch(User, query, :post_title, titles, repo_opts)`

**Comment by benwilson512** [comment]
Yeah ok, went ahead and did that, which although we're at 5 args (ugh) actually has a nice flow:

```
run_batch(ThingToBatch, query_for_thing, :batch_by_this, values, opts)
```

**Comment by amcvitty** [comment]
I just came across the issue that :through associations don't work myself.

I don't see anyone answering Ben's question
> Why do through associations not match the queryable line?

So - I wrote a test that demonstrates the issue (PR #15).

I also had a quick look at the underlying issue.

Line 241 of dataloader/ecto.ex is querying the __struct__ matching on 
```
case schema.__schema__(:association, assoc_field) do
     %{queryable: queryable, field: field} -> ...
```
And that works when the field is a `%Ecto.Association.Has`, but if it's a `%Ecto.Association.HasThrough`, it doesn't have the `queryable`. It instead has a `through`

I wonder if this gets tricky, because we might need to make use of the query/2 for each queryable at every step of the chain, rather than just once.

**Comment by benwilson512** [comment]
Hey @amcvitty.

This is the key point:

> we might need to make use of the query/2

Fortunately, I don't think we need to do this. The thing we can guarantee with the `query/2` function is that if you ask for queryable X, rules from `query/2` will be applied because we'll pass in X. What we can't guarantee is anything about ecto queries that pass _through_ X on their way Y. We can't guarantee this with custom batch functions, and we can't guarantee this with through.

Ultimately if you're using the association based helpers you're going to get Ecto association based lookup characteristics, and you can't actually customize the intermediary lookups with that either.

https://github.com/absinthe-graphql/dataloader/pull/11/commits/3f6fae94d297d1c14cdce6dd15a86ad36be28504 provides working `through` association handling.
